[package]
name = "temp2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
rand = "0.8.5"
rppal = "0.14.1"
tokio = "1.28.1"
tui = "0.19.0"
